### ISSUE TITLE
Uncaught exception: Invalid_argument("Char.chr")

### ISSUE THREAD

**Issue by rbardou** [mirleft/ocaml-tls#377]
First of all thanks for all the work you put in this set of libraries :)

I get an uncaught exception: `Invalid_argument("Char.chr")` when trying to connect from a Raspberry Pi. I think it comes from the `Uncommon` module of nocrypto, function `set_msb`.

This happens when I try to connect to bardou.ovh port 443 or imap.bardou.ovh port 993, not google.com port 443. Maybe something is wrong with bardou.ovh but in any case, having a more explicit error message would be nice.

It only happens on my Raspberry Pi. I don't know if this is due to my OCaml version or the Raspberry Pi architecture though. This is with OCaml 4.02.2.

To reproduce:

```
(* ocamlbuild -tag debug -pkg tls.lwt test_tls.byte -- *)

open Lwt

let host = "bardou.ovh", 443

let () =
  Printexc.record_backtrace true;
  try
    Lwt_main.run (
      Tls_lwt.connect X509.Authenticator.null host >>= fun (ic, oc) ->
      Lwt_io.write oc "GET / HTTP/1.1\r\n\r\n" >>= fun () ->
      Lwt_io.read_line ic >>= fun line ->
      Printf.printf "received: %S\n%!" line;
      return ()
    )
  with exn ->
    Printexc.print_backtrace stdout;
    print_endline (Printexc.to_string exn)
```

This is a minimal example with Lwt, but I originally had the problem without Lwt (just Tls.Engine).

If you cannot reproduce, I could try to store the data that I receive from the remote host and make another minimal example which does not try to connect to the network, but I don't know if it may reveal sensitive information?

**Comment by hannesm** [comment]
thanks for the report and the example code, I'm not sure what the issue is.  On my amd64 FreeBSD laptop (with OCaml 4.06.0), your example works and I see output: `received: "HTTP/1.1 400 Bad Request"` (if I add a `Host: foo\r\n` in the string literal, I see the following output: `received: "HTTP/1.1 404 Not Found"`).

which raspberry pi do you use? it may be a 32bit architecture (which I don't have a test platform atm), or some issue on arm platforms.  I'll try on the weekend to revive my cubieboard (which is arm32) and reproduce, unless you manage to debug it further yourself.

**Comment by rbardou** [comment]
It is a raspberry pi 2, which I believe is indeed an arm32 architecture.
```
# max_int;;
- : int = 1073741823
```
Thanks for looking into this :)

**Comment by cfcs** [comment]
@rbardou I can't reproduce this either. It would be very helpful to know which versions of `nocrypto` and `cstruct` and `ocplib-endian` you have installed, you can find this information with `opam show nocrypto cstruct ocplib-endian`.
This should give you the `upstream-checksum`, `upstream-url` and `installed-versions` fields that can help us figure out what's going on.

In my nocrypto checkout, I have this definition:
```ocaml
  let set_msb bits cs =
    if bits > 0 then (* cfcs: with cannot be smaller than 0 *)
      let n = len cs in
      let rec go width = function
        | i when i = n     -> ()
        | i when width < 8 -> (*cfcs: width is thus bound to be 0;1; ... ;7 *)
            set_uint8 cs i (get_uint8 cs i lor (0xff lsl (8 - width)))
            (* ^-- cfcs: so 0xff is shifted between 8 and 1 times.
                     This relies on `set_uint8` to silently truncate the integer. See note below. *)
        | i -> (* cfcs: so if width >= 8 *)
            set_uint8 cs i 0xff ; go (width - 8) (succ i) in
      go bits 0
```

The only place I can see `Char.chr` conceivably being used is in `set_uint8`, and `0xff` should be good, so to test the hypothesis of Cstruct being the culprit, you could try changing the line with the shifts to:
```ocaml
            set_uint8 cs i (0xff land (get_uint8 cs i lor (0xff lsl (8 - width))))
```

### Cstruct.set_uint8
`set_msb` calls out to `Cstruct.set_uint8`, relying on a silent integer truncation to happen in there.
That behavior is not documented, but it is present in my version, the definition looks like this:
```ocaml
let set_uint8 t i c =
  if i >= t.len || i < 0 then err_invalid_bounds "set_uint8" t i 1
  else Bigarray.Array1.set t.buffer (t.off+i) (Char.unsafe_chr c)
```

`Char.unsafe_chr` is a kind of interesting function, since it doesn't truncate the integer directly, consider:
```
utop # let xxx = Char.unsafe_chr (0x1234);;
val xxx : char = '\^60'
─( 16:29:14 )─< command 2 >──────────────────────────────────────{ counter: 0 }─
utop # Char.code xxx;;
- : int = 4660
(* For more fun try Char.unsafe_chr (-2);; - I think it's a crappy function to be using this lightly. *)
```

So the actual truncation happens in the `Bigarray.Array1` module because the backing type for `Cstruct.buffer` is `Bigarray.int8_unsigned_elt`.

So I wonder how you ended up with `Invalid_argument("Char.chr")`.
`Cstruct` is not supported on `OCaml 4.02.2`, the last commit with support for that was
```
:~/ocaml/cstruct$ git show HEAD~56
commit 3d2722c5b4ee0076fb206cc21490cd7924be61ec
Merge: 6a2070b 34f4146
Author: Dave Scott <djs55@users.noreply.github.com>
Date:   Sat Mar 12 16:35:12 2016 +0000
```
The last release for your version:
```
:~/ocaml/cstruct$ git show HEAD~63
commit 1acae5d8e41dab104384b0178c454f2ac9250251 (tag: v1.9.0)
Merge: cc9af43 79b68dc
Author: Anil Madhavapeddy <anil@recoil.org>
Date:   Fri Feb 19 17:22:55 2016 +0000

    Merge pull request #82 from avsm/1.9.0
    
    release 1.9.0
```

The commit has:
```ocaml
let set_uint8 t i c =
  if i >= t.len || i < 0 then err_invalid_bounds "set_uint8" t i 1
  else EndianBigstring.BigEndian.set_int8 t.buffer (t.off+i) c
```

`EndianBigstring` seems to originate from `ocplib-endian`. The last commit that used `Char.chr` there was 
```shell
:~/triage/ocplib-endian/src$ git show HEAD~21
commit c2e054282a5125a2bcfd0ed89eadfa354d3926ff (tag: 0.4)
Author: Pierre Chambart <pierre.chambart@ocamlpro.org>
Date:   Mon Aug 5 13:49:43 2013 +0200

    Bump version to 0.4
```

So I wonder if you're using `ocplib-endian.0.4`, `cstruct.1.9.0`, that would explain things to me.
As far as I can tell the last commits that didn't bound `cstruct` to be a recent version was:

```
git show HEAD~57
commit a0474bd1600dcfd353a3c3c852463b63b63ebf4c (samoht/master, hannes/master, cfcs/master)
Author: pqwy <david@numm.org>
Date:   Thu Feb 23 16:35:33 2017 +0000
```

The last release made before that commit was, `v0.5.4`, ie the latest version of `nocrypto` from January 2017.
```
git show HEAD~61
commit 1c4fb7aaefcd9bd78dc6f7c53906eafcd7f94496 (tag: v0.5.4)
Author: pqwy <david@numm.org>
Date:   Tue Jan 31 23:32:35 2017 +0000
```

So sadly I think `nocrypto` will stop working entirely on your compiler version if `nocrypto` ever sees a new release, and I think your current issues are caused by running a 5 year old version of `ocplib-endian`. **Try upgrading to `OCaml 4.03.0`, or `4.04.2` if you can.**

**Comment by cfcs** [comment]
PS: I assume you're on `tls.0.8.0` or earlier, since `0.9.0` seems to have a lower bound on `cstruct.0.3.0` ?

**Comment by rbardou** [comment]
Thank you for your response and sorry for the delay, I just noticed it.

Indeed it seems the versions which were chosen by the solver are quite old:
nocrypto version 0.5.0
cstruct version 1.6.0
ocplib-endian version 0.4
tls version 0.6.0

I just tried to switch to OCaml 4.06.1 but I fail to link with ptime. It seems the version of glibc I have is too old and ptime should be linked with -lrt to be able to use symbol clock_gettime (newer versions of glibc don't need that). I use raspbian jessie. I need to upgrade. It will probably take some time but I'll try to update this ticket after that. I'm sure this particular issue will be fixed :) I could also try to opam pin some patch with -lrt, depending on my mood.

Thanks again!

**Comment by hannesm** [comment]
thanks for your report, are there any news (over the last 1.5 years)? ocaml-tls and mirage-crypto moved over to OCaml 4.07.0. This may still be an issue since I don't think anyone uses the stack on 32bit (nor on ARM). If you happen to find the time to retry a more current stack (mirage-crypto based, tls 0.11.0) and reproduce the issue, please reopen.
