### ISSUE TITLE
Excessive log spam at info level

### ISSUE THREAD

**Issue by talex5** [mirleft/ocaml-tls#436]
TLS likes to print a message like this when it make a TLS connection:
```
2021-07-22 16:14.33     tls.config [INFO] client with ((ciphers
  (AES_128_GCM_SHA256 AES_256_GCM_SHA384 CHACHA20_POLY1305_SHA256
   AES_128_CCM_SHA256 DHE_RSA_WITH_AES_256_GCM_SHA384
   DHE_RSA_WITH_AES_128_GCM_SHA256 DHE_RSA_WITH_AES_256_CCM
   DHE_RSA_WITH_AES_128_CCM DHE_RSA_WITH_CHACHA20_POLY1305_SHA256
   ECDHE_RSA_WITH_AES_128_GCM_SHA256 ECDHE_RSA_WITH_AES_256_GCM_SHA384
   ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
   ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
   ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256))
 (protocol_versions (TLS_1_2 TLS_1_3))
 (signature_algorithms
  (ECDSA_SECP256R1_SHA256 ECDSA_SECP384R1_SHA384 ECDSA_SECP521R1_SHA512
   ED25519 RSA_PSS_RSAENC_SHA256 RSA_PSS_RSAENC_SHA384 RSA_PSS_RSAENC_SHA512
   RSA_PKCS1_SHA256 RSA_PKCS1_SHA384 RSA_PKCS1_SHA512 RSA_PKCS1_SHA224
   ECDSA_SECP256R1_SHA1 RSA_PKCS1_SHA1 RSA_PKCS1_MD5))
 (use_reneg false) (authenticator (Authenticator)) (peer_name ())
 (own_certificates None) (acceptable_cas ()) (session_cache SESSION_CACHE)
 (ticket_cache TICKET_CACHE) (cached_session ()) (cached_ticket ())
 (alpn_protocols ())
 (groups
  (X25519 P384 P256 P521 FFDHE2048 FFDHE3072 FFDHE4096 FFDHE6144 FFDHE8192))
 (zero_rtt 0))
```
I was going to change the default log-level for tls in my services to suppress it, but I thought I'd check here first in case it's accidental and this was supposed to be debug-level. If it's intentional, feel free to close this issue.

**Comment by hannesm** [comment]
This behaviour was introduced in tls 0.13.0 (3f1f866aea251187264e7a3b245b8b2510004a83). Whenever a client or server is created, a log message is emitted at the info level. The reason is (for the server side at least) that some configuration fields are compacted (some variants removed) depending on the available certificates (no ECDSA signature algorithms if a RSA certificate is used).

On the one hand, for clients this may be a bit verbose. On the other hand, it depends on the default log level (which in the Logs library is warn/error/app). I agree that for the client this is less helpful, and would be fine to change it to debug level.

**Comment by talex5** [comment]
Great - thanks!
