### ISSUE TITLE
mac mismatch error

### ISSUE THREAD

**Issue by joprice** [mirleft/ocaml-tls#481]
I'm trying out the new eio cohttp client and hit an `MAC mismatch` error:

```+TLS failure: MAC mismatch
+Raised at Tls_eio.Raw.read_react in file "eio/tls_eio.ml", line 74, characters 19-26
+Called from Tls_eio.Raw.drain_handshake in file "eio/tls_eio.ml", line 133, characters 17-29
+Called from Tls_eio.client_of_flow in file "eio/tls_eio.ml" (inlined), line 228, characters 39-75
```

I can provide more details on my setup if it helps repro.

**Comment by hannesm** [comment]
Thanks for your report, would you mind to elaborate on (a) a test case that you have (i.e. which remote server you're trying to connect to)? (b) which tls & mirage-crypto versions you use? (c) on which platform you are?

Since you're using a http client, would you mind to try on the same machine & opam switch an `opam install http-lwt-client` and run `hurl https://<server>`, and report success or failure with that (taking eio and cohttp out of the chain to figure out where the issue is located)?

**Comment by hannesm** [comment]
Dear @joprice, any chance you could "provide more details", as requested 2 weeks ago?

**Comment by joprice** [comment]
Yes, I can provide more details with a reproduction within a day or so.

**Comment by joprice** [comment]
Unfortunately, I can no longer reproduce with any setup. I'll reopen if I encounter it again and can reproduce successfully.
